version: "3.7"

services:
  envoy:
    image: docker.io/envoyproxy/envoy-alpine:v1.14.2
    command: /usr/local/bin/envoy -c etc/envoy/envoy-docker.yaml -l debug --service-cluster front --service-node front
    volumes:
      - './config/certs:/etc/certs:ro'
      - './config/base/envoy/config:/etc/envoy:ro'
    expose:
      - '9090'
      - '9443'
      - '9901'
    ports:
      - '9090:9090'
      - '9444:9443'
      - '9901:9901'

  envoy_http:
    image: docker.io/envoyproxy/envoy-alpine:v1.14.2
    command: /usr/local/bin/envoy -c etc/envoy/envoy-docker-http.yaml -l debug --service-cluster front --service-node front
    volumes:
      - './config/certs:/etc/certs:ro'
      - './config/base/envoy/config:/etc/envoy:ro'
    expose:
      - '9090'
      - '9443'
      - '9901'
    ports:
      - '9090:9090'
      - '9444:9443'
      - '9901:9901'

  envoy_secure_backend:
    image: docker.io/envoyproxy/envoy-alpine:v1.14.2
    command: /usr/local/bin/envoy -c etc/envoy/envoy-docker-secure-backend.yaml -l debug --service-cluster front --service-node front
    volumes:
      - './config/certs:/etc/certs:ro'
      - './config/base/envoy/config:/etc/envoy:ro'
    expose:
      - '9090'
      - '9443'
      - '9901'
    ports:
      - '9090:9090'
      - '9444:9443'
      - '9901:9901'

  envoy_secure_backend_cleint_cert:
    image: docker.io/envoyproxy/envoy-alpine:v1.14.2
    command: /usr/local/bin/envoy -c etc/envoy/envoy-docker-secure-backend-client-cert.yaml -l debug --service-cluster front --service-node front
    volumes:
      - './config/certs:/etc/certs:ro'
      - './config/base/envoy/config:/etc/envoy:ro'
    expose:
      - '9090'
      - '9443'
      - '9901'
    ports:
      - '9090:9090'
      - '9444:9443'
      - '9901:9901'

  espv2:
    image: gcr.io/endpoints-release/endpoints-runtime:2.13.0
    command:
      - "--service=<SERVICE_NAME>"
      - "--rollout_strategy=managed"
      - "--listener_port=8089"
      - "--backend=grpc://127.0.0.1:50042"
      - "--service_account_key=/.google-devcredentials.json"
      - "--cors_preset=basic"
      # frontend host+port
      - "--cors_allow_origin=http://0.0.0.0:4242"
      - "--non_gcp"
      - "--enable_debug"
#      - "--log_jwt_payloads=aud,iss"
#      - "--log_request_headers=referer"
    expose:
      - '8080'
    ports:
      - "8089:8089"
      - "8080:8080"
#    volumes:
#      - ./.google-devcredentials.json:/.google-devcredentials.json:ro
#    environment:
#      - DEFAULT_BACKEND=http://127.0.0.1:8082
