# example https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/skaffold.yaml
# schema https://skaffold.dev/docs/references/yaml/

apiVersion: skaffold/v2beta27
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
      env:
      - GOPROXY={{.GOPROXY}}
#  ko:
#    fromImage: gcr.io/distroless/base:debug-nonroot
#    env:
#      - GOPRIVATE=git.internal.example.com,source.developers.google.com
#      - GOPROXY={{.GOPROXY}}
#    platforms:
#      - linux/amd64
#    labels:
#      org.opencontainers.image.licenses: Apache-2.0
#      org.opencontainers.image.source: https://github.com/xmlking/grpc-starter-kit
#      org.opencontainers.image.source: "{{.GITHUB_SERVER_URL}}/{{.GITHUB_REPOSITORY}}

profiles:
- name: gcb
  build:
    googleCloudBuild: {}
#- name: gcb
#  build:
#    googleCloudBuild:
#      diskSizeGb: 300
#      machineType: N1_HIGHCPU_32
#      timeout: 4000s
