# https://taskfile.dev

version: '3'

vars:
  PROTO_IN:           proto/mkit
  PROTO_OUT:          mkit
  GITHUB_REPO_OWNER:  xmlking
  GITHUB_REPO_NAME:   grpc-starter-kit
  GITHUB_REPO_URL:    https://github.com/{{.GITHUB_REPO_OWNER}}/{{.GITHUB_REPO_NAME}}.git
  GOPATH:
    sh: go env GOPATH
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  GIT_DIRTY:
    sh: git status --porcelain 2> /dev/null
  ALL_GO_MOD_DIRS:
#    sh: find . -type f -name 'go.mod' -exec dirname {} \;  | sort
    sh: find * -name 'go.mod' -mindepth 1 -exec dirname {} \; | sort

env:
  FOO: foo

includes:
  config:     ./config
  proto:      task/proto.yml
  go:         task/go.yml
  mod:        task/mod.yml
  install:    task/install.{{OS}}.yml
  build:      task/build.{{OS}}.yml

tasks:
  proto:
    desc: Lint, Clean and Generate go code from protos.
    cmds:
      - task: proto:default

  default:
    desc: Lint, Clean and Generate go code from protos.
    cmds:
      - task: proto:default
      - task: build:build
      - task: config:deploy
