// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mkit/service/account/profile/v1/profile_service.proto

package profilev1

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	v1 "github.com/xmlking/grpc-starter-kit/mkit/service/account/entities/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FIXME: https://github.com/envoyproxy/protoc-gen-validate/issues/223
// Workaround in .override.go
type ListRequest struct {
	Limit                *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	PreferredTheme       *wrappers.StringValue `protobuf:"bytes,4,opt,name=preferred_theme,json=preferredTheme,proto3" json:"preferred_theme,omitempty"`
	Gender               v1.Profile_GenderType `protobuf:"varint,5,opt,name=gender,proto3,enum=mkit.service.account.entities.v1.Profile_GenderType" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f12aaf9ed8446289, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetLimit() *wrappers.UInt32Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *ListRequest) GetPage() *wrappers.UInt32Value {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *ListRequest) GetSort() *wrappers.StringValue {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *ListRequest) GetPreferredTheme() *wrappers.StringValue {
	if m != nil {
		return m.PreferredTheme
	}
	return nil
}

func (m *ListRequest) GetGender() v1.Profile_GenderType {
	if m != nil {
		return m.Gender
	}
	return v1.Profile_GENDER_TYPE_UNSPECIFIED
}

type ListResponse struct {
	Results              []*v1.Profile `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total                uint32        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f12aaf9ed8446289, []int{1}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetResults() []*v1.Profile {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GetRequest struct {
	// Types that are valid to be assigned to Id:
	//	*GetRequest_ProfileId
	//	*GetRequest_UserId
	Id                   isGetRequest_Id `protobuf_oneof:"id"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f12aaf9ed8446289, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type isGetRequest_Id interface {
	isGetRequest_Id()
}

type GetRequest_ProfileId struct {
	ProfileId *wrappers.StringValue `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3,oneof"`
}

type GetRequest_UserId struct {
	UserId *wrappers.StringValue `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof"`
}

func (*GetRequest_ProfileId) isGetRequest_Id() {}

func (*GetRequest_UserId) isGetRequest_Id() {}

func (m *GetRequest) GetId() isGetRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetRequest) GetProfileId() *wrappers.StringValue {
	if x, ok := m.GetId().(*GetRequest_ProfileId); ok {
		return x.ProfileId
	}
	return nil
}

func (m *GetRequest) GetUserId() *wrappers.StringValue {
	if x, ok := m.GetId().(*GetRequest_UserId); ok {
		return x.UserId
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetRequest_ProfileId)(nil),
		(*GetRequest_UserId)(nil),
	}
}

type GetResponse struct {
	Result               *v1.Profile `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f12aaf9ed8446289, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetResult() *v1.Profile {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateRequest struct {
	UserId               *wrappers.StringValue `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tz                   *wrappers.StringValue `protobuf:"bytes,3,opt,name=tz,proto3" json:"tz,omitempty"`
	Avatar               *wrappers.StringValue `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender               v1.Profile_GenderType `protobuf:"varint,5,opt,name=gender,proto3,enum=mkit.service.account.entities.v1.Profile_GenderType" json:"gender,omitempty"`
	Birthday             *timestamp.Timestamp  `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	PreferredTheme       *wrappers.StringValue `protobuf:"bytes,7,opt,name=preferred_theme,json=preferredTheme,proto3" json:"preferred_theme,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f12aaf9ed8446289, []int{4}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *CreateRequest) GetTz() *wrappers.StringValue {
	if m != nil {
		return m.Tz
	}
	return nil
}

func (m *CreateRequest) GetAvatar() *wrappers.StringValue {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *CreateRequest) GetGender() v1.Profile_GenderType {
	if m != nil {
		return m.Gender
	}
	return v1.Profile_GENDER_TYPE_UNSPECIFIED
}

func (m *CreateRequest) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *CreateRequest) GetPreferredTheme() *wrappers.StringValue {
	if m != nil {
		return m.PreferredTheme
	}
	return nil
}

type CreateResponse struct {
	Result               *v1.Profile `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f12aaf9ed8446289, []int{5}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetResult() *v1.Profile {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "mkit.service.account.profile.v1.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "mkit.service.account.profile.v1.ListResponse")
	proto.RegisterType((*GetRequest)(nil), "mkit.service.account.profile.v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "mkit.service.account.profile.v1.GetResponse")
	proto.RegisterType((*CreateRequest)(nil), "mkit.service.account.profile.v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "mkit.service.account.profile.v1.CreateResponse")
}

func init() {
	proto.RegisterFile("mkit/service/account/profile/v1/profile_service.proto", fileDescriptor_f12aaf9ed8446289)
}

var fileDescriptor_f12aaf9ed8446289 = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xc7, 0x3b, 0x8e, 0xe3, 0x34, 0x27, 0x6d, 0xae, 0x34, 0xba, 0xd2, 0xb5, 0xa2, 0x2b, 0x1a,
	0x45, 0x42, 0x0a, 0xa5, 0xd8, 0x24, 0x05, 0x09, 0x90, 0xf8, 0xa8, 0xbb, 0x08, 0x95, 0x58, 0x54,
	0x6e, 0x8b, 0x50, 0x37, 0x65, 0x1a, 0x9f, 0xa6, 0xa3, 0x3a, 0xb6, 0x19, 0x4f, 0x8c, 0xda, 0x25,
	0xbc, 0x00, 0x4f, 0xc0, 0x33, 0x20, 0x1e, 0x81, 0x25, 0x4f, 0x84, 0xb2, 0x42, 0xb6, 0xc7, 0xa1,
	0x40, 0xab, 0xb8, 0x88, 0xee, 0x26, 0x99, 0xf3, 0x3b, 0xe7, 0x3f, 0xe7, 0xcb, 0x70, 0x7f, 0x7c,
	0xc2, 0xa5, 0x1d, 0xa3, 0x48, 0xf8, 0x10, 0x6d, 0x36, 0x1c, 0x86, 0x93, 0x40, 0xda, 0x91, 0x08,
	0x8f, 0xb8, 0x8f, 0x76, 0xd2, 0x2b, 0x8e, 0x07, 0xca, 0xc4, 0x8a, 0x44, 0x28, 0x43, 0xba, 0x92,
	0x62, 0x56, 0xf1, 0x9f, 0xc2, 0x2c, 0x65, 0x6b, 0x25, 0xbd, 0xd6, 0xca, 0x28, 0x0c, 0x47, 0x3e,
	0xda, 0x99, 0xf9, 0xe1, 0xe4, 0xc8, 0x96, 0x7c, 0x8c, 0xb1, 0x64, 0xe3, 0x28, 0xf7, 0xd0, 0xba,
	0xf1, 0xab, 0xc1, 0x5b, 0xc1, 0xa2, 0x08, 0x45, 0xac, 0xee, 0xed, 0x0b, 0x85, 0x61, 0x20, 0xb9,
	0xe4, 0x18, 0xa7, 0xca, 0x8a, 0xb3, 0x02, 0xfe, 0x4b, 0x98, 0xcf, 0x3d, 0x26, 0xd1, 0x2e, 0x0e,
	0xf9, 0x45, 0xe7, 0x7d, 0x05, 0x1a, 0x2f, 0x78, 0x2c, 0x5d, 0x7c, 0x33, 0xc1, 0x58, 0xd2, 0xc7,
	0x50, 0xf5, 0xf9, 0x98, 0x4b, 0x93, 0xb4, 0x49, 0xb7, 0xd1, 0xff, 0xdf, 0xca, 0x95, 0x58, 0x85,
	0x12, 0x6b, 0x6f, 0x2b, 0x90, 0xeb, 0xfd, 0x97, 0xcc, 0x9f, 0xa0, 0x53, 0x9f, 0x3a, 0xc6, 0xaa,
	0x6e, 0x7a, 0x5d, 0xe2, 0xe6, 0x14, 0x7d, 0x08, 0x7a, 0xc4, 0x46, 0x68, 0x6a, 0x25, 0xe8, 0xda,
	0xd4, 0xd1, 0x57, 0xb5, 0x2e, 0x71, 0x33, 0x84, 0xde, 0x05, 0x3d, 0x0e, 0x85, 0x34, 0x2b, 0x97,
	0xa0, 0x3b, 0x52, 0xf0, 0x60, 0x94, 0xa1, 0x6e, 0x66, 0x49, 0x7d, 0xf8, 0x27, 0x12, 0x78, 0x84,
	0x42, 0xa0, 0x77, 0x20, 0x8f, 0x71, 0x8c, 0xa6, 0x3e, 0x1f, 0x76, 0x6e, 0x4e, 0x9d, 0x8e, 0x68,
	0xbb, 0xba, 0xc7, 0xc4, 0x49, 0xaa, 0x7b, 0x74, 0x2c, 0x5d, 0x63, 0x18, 0xc6, 0x63, 0x3e, 0x74,
	0xeb, 0xc3, 0x50, 0x44, 0xa1, 0x60, 0x12, 0xdd, 0xe6, 0xcc, 0xf7, 0x6e, 0xea, 0x9a, 0xee, 0x83,
	0x31, 0xc2, 0xc0, 0x43, 0x61, 0x56, 0xdb, 0xa4, 0xdb, 0xec, 0xdf, 0xb3, 0x2e, 0x2c, 0xf3, 0x2c,
	0xf1, 0x49, 0xcf, 0xda, 0x56, 0x25, 0x1f, 0x64, 0xdc, 0xee, 0x69, 0x84, 0xce, 0xd2, 0xd4, 0xa9,
	0xbf, 0x23, 0x86, 0xb9, 0x60, 0x12, 0x53, 0x73, 0x95, 0xc7, 0x4e, 0x00, 0x4b, 0x79, 0x11, 0xe2,
	0x28, 0x0c, 0x62, 0xa4, 0x9b, 0x50, 0x13, 0x18, 0x4f, 0x7c, 0x19, 0x9b, 0xa4, 0x5d, 0xe9, 0x36,
	0xfa, 0xb7, 0x4a, 0x07, 0x73, 0x0b, 0x92, 0xfe, 0x0b, 0x55, 0x19, 0x4a, 0xe6, 0x67, 0xc5, 0x58,
	0x76, 0xf3, 0x1f, 0x8f, 0x2a, 0xdf, 0x1c, 0xd2, 0xf9, 0x48, 0x00, 0x06, 0x38, 0x2b, 0xfa, 0x00,
	0xa0, 0xe8, 0x64, 0xee, 0x5d, 0x5a, 0xf9, 0xf3, 0x39, 0x5c, 0x9c, 0x3a, 0x55, 0x51, 0xf9, 0x44,
	0xc8, 0xf3, 0x05, 0xb7, 0xae, 0xd8, 0x2d, 0x8f, 0x6e, 0x40, 0x6d, 0x12, 0xa3, 0x48, 0xbd, 0x68,
	0x57, 0xf4, 0x62, 0xa4, 0xe0, 0x96, 0xe7, 0xe8, 0xa0, 0x71, 0xaf, 0xb3, 0x07, 0x8d, 0x4c, 0x9f,
	0xca, 0xc7, 0x06, 0x18, 0xf9, 0xab, 0x94, 0xb8, 0x2b, 0xa4, 0x43, 0x81, 0xf9, 0xbb, 0xbf, 0x56,
	0x60, 0x79, 0x53, 0x60, 0x5a, 0x5e, 0xf5, 0xf4, 0xa7, 0x7f, 0xa8, 0xb8, 0xd0, 0x4b, 0xd7, 0x40,
	0x93, 0x67, 0xa5, 0x9a, 0x56, 0x93, 0x67, 0xf4, 0x09, 0x18, 0x2c, 0x61, 0x92, 0x89, 0x52, 0x9d,
	0x9a, 0x47, 0xfb, 0x90, 0x46, 0xcb, 0xa9, 0xeb, 0x6c, 0x42, 0xfa, 0x0c, 0x16, 0x0f, 0xb9, 0x90,
	0xc7, 0x1e, 0x3b, 0x35, 0x8d, 0x4c, 0x5d, 0xeb, 0x37, 0x75, 0xbb, 0xc5, 0xa2, 0xca, 0xb4, 0x7d,
	0x26, 0xda, 0x03, 0xe2, 0xce, 0xa8, 0x8b, 0x06, 0xb2, 0x76, 0x6d, 0x03, 0xd9, 0x79, 0x05, 0xcd,
	0xa2, 0x96, 0x7f, 0xb7, 0x4d, 0xfa, 0x5f, 0x34, 0x68, 0xaa, 0x8b, 0x9d, 0x9c, 0xa5, 0x43, 0xd0,
	0xd3, 0x09, 0xa5, 0x6b, 0xd6, 0x9c, 0xe5, 0x6e, 0x9d, 0xdb, 0xa6, 0xad, 0x3b, 0x25, 0xad, 0x95,
	0xfe, 0xd7, 0x50, 0x19, 0xa0, 0xa4, 0xb7, 0xe7, 0x52, 0x3f, 0x66, 0xb7, 0xb5, 0x56, 0xce, 0x58,
	0x45, 0xe0, 0x60, 0xe4, 0x39, 0xa3, 0xd6, 0x5c, 0xee, 0xa7, 0x41, 0x69, 0xd9, 0xa5, 0xed, 0xf3,
	0x50, 0x8e, 0x05, 0xf3, 0xbe, 0x83, 0xdb, 0x64, 0xbf, 0xd8, 0x1d, 0x49, 0xef, 0xd0, 0xc8, 0x7a,
	0x63, 0xfd, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xd9, 0x03, 0x64, 0x75, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type profileServiceClient struct {
	cc *grpc.ClientConn
}

func NewProfileServiceClient(cc *grpc.ClientConn) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/mkit.service.account.profile.v1.ProfileService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/mkit.service.account.profile.v1.ProfileService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/mkit.service.account.profile.v1.ProfileService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedProfileServiceServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedProfileServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mkit.service.account.profile.v1.ProfileService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mkit.service.account.profile.v1.ProfileService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mkit.service.account.profile.v1.ProfileService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mkit.service.account.profile.v1.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ProfileService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProfileService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ProfileService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mkit/service/account/profile/v1/profile_service.proto",
}
