database:
  dialect: sqlite3
  host: 0.0.0.0
  port: 9999
  username: sumo
  password: demo
  database: "file:account?mode=memory&cache=shared&_fk=1"
  max_open_conns: 1
  max_idle_conns: 1
  conn_max_lifetime: 1h
  logging: true
email:
  username: yourGmailUsername
  password: yourGmailAppPassword
  email_server: smtp.gmail.com
  port: 587
  from: from@gmail.com

services:
  account:
    authority: "account-service"
    version: v0.1.0
    endpoint: dns:///localhost:8080
    metadata:
      tenant_id: sumanth
  greeter:
    authority: "greeter-service"
    version: v0.1.0
    endpoint: dns:///localhost:8081
#    endpoint: unix:///tmp/greeter.sock
    service_config: |
      {
        "loadBalancingPolicy": "round_robin",
        "methodConfig": [
        {
          "name": [
          {
            "service": "mkit.service.greeter.v1.GreeterService",
            "method": "Hello"
          }
          ],
          "waitForReady": false,
          "retryPolicy": {
            "maxAttempts": 3,
            "initialBackoff": "2.1s",
            "maxBackoff": "2.2s",
            "backoffMultiplier": 3,
            "retryableStatusCodes": [
              "UNAVAILABLE",
              "RESOURCE_EXHAUSTED"
            ]
          }
        }
        ],
        "retryThrottling": {
          "maxTokens": 10,
          "tokenRatio": 0.1
        }
      }
  emailer:
    authority: "emailer-service"
    version: v0.1.0
    endpoint: http://localhost:8082
  recorder:
    authority: "recorder-service"
    version: v0.1.0
    endpoint: http://localhost:8083
  play:
    authority: "play-service"
    version: v0.1.0
    endpoint: http://localhost:8084

features:
  metrics:
    enabled: false
    target: stdout
    endpoint: ":2222"
    sampling_fraction: 1.0
    collect_period: 10s
  tracing:
    enabled: false
    target: stdout
    endpoint: "jaeger:6831"
    sampling_fraction:  1.0
  tls:
    cert_file: config/certs/upstream-localhost-cert.pem
    key_file: config/certs/upstream-localhost-key.pem
    ca_file: config/certs/upstream-ca-cert.pem
    server_name: "localhost"
    enabled: true
  validator:
    enabled: true
  rpclog:
    enabled: true
  translog:
    topic: mkit.service.recorder
    enabled: true
