// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mkit/shared/config/v1/config.proto

package configv1

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DatabaseDialect int32

const (
	DatabaseDialect_DATABASE_DIALECT_UNSPECIFIED DatabaseDialect = 0
	DatabaseDialect_DATABASE_DIALECT_POSTGRE     DatabaseDialect = 1
	DatabaseDialect_DATABASE_DIALECT_MY_SQL      DatabaseDialect = 2
	DatabaseDialect_DATABASE_DIALECT_SQ_LITE3    DatabaseDialect = 3
)

var DatabaseDialect_name = map[int32]string{
	0: "DATABASE_DIALECT_UNSPECIFIED",
	1: "DATABASE_DIALECT_POSTGRE",
	2: "DATABASE_DIALECT_MY_SQL",
	3: "DATABASE_DIALECT_SQ_LITE3",
}

var DatabaseDialect_value = map[string]int32{
	"DATABASE_DIALECT_UNSPECIFIED": 0,
	"DATABASE_DIALECT_POSTGRE":     1,
	"DATABASE_DIALECT_MY_SQL":      2,
	"DATABASE_DIALECT_SQ_LITE3":    3,
}

func (x DatabaseDialect) String() string {
	return proto.EnumName(DatabaseDialect_name, int32(x))
}

func (DatabaseDialect) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{0}
}

type Service struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Deadline             uint32   `protobuf:"varint,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetDeadline() uint32 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

type EmailConfiguration struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	EmailServer          string   `protobuf:"bytes,3,opt,name=email_server,json=emailServer,proto3" json:"email_server,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	From                 string   `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailConfiguration) Reset()         { *m = EmailConfiguration{} }
func (m *EmailConfiguration) String() string { return proto.CompactTextString(m) }
func (*EmailConfiguration) ProtoMessage()    {}
func (*EmailConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{1}
}

func (m *EmailConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailConfiguration.Unmarshal(m, b)
}
func (m *EmailConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailConfiguration.Marshal(b, m, deterministic)
}
func (m *EmailConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailConfiguration.Merge(m, src)
}
func (m *EmailConfiguration) XXX_Size() int {
	return xxx_messageInfo_EmailConfiguration.Size(m)
}
func (m *EmailConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_EmailConfiguration proto.InternalMessageInfo

func (m *EmailConfiguration) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *EmailConfiguration) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EmailConfiguration) GetEmailServer() string {
	if m != nil {
		return m.EmailServer
	}
	return ""
}

func (m *EmailConfiguration) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *EmailConfiguration) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

type DatabaseConfiguration struct {
	Dialect              DatabaseDialect    `protobuf:"varint,1,opt,name=dialect,proto3,enum=mkit.shared.config.v1.DatabaseDialect" json:"dialect,omitempty"`
	Host                 string             `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32             `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username             string             `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string             `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Database             string             `protobuf:"bytes,6,opt,name=database,proto3" json:"database,omitempty"`
	Charset              string             `protobuf:"bytes,7,opt,name=charset,proto3" json:"charset,omitempty"`
	Utc                  bool               `protobuf:"varint,8,opt,name=utc,proto3" json:"utc,omitempty"`
	Logging              bool               `protobuf:"varint,9,opt,name=logging,proto3" json:"logging,omitempty"`
	Singularize          bool               `protobuf:"varint,10,opt,name=singularize,proto3" json:"singularize,omitempty"`
	MaxOpenConns         uint32             `protobuf:"varint,11,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	MaxIdleConns         uint32             `protobuf:"varint,12,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	ConnMaxLifetime      *duration.Duration `protobuf:"bytes,13,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DatabaseConfiguration) Reset()         { *m = DatabaseConfiguration{} }
func (m *DatabaseConfiguration) String() string { return proto.CompactTextString(m) }
func (*DatabaseConfiguration) ProtoMessage()    {}
func (*DatabaseConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{2}
}

func (m *DatabaseConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseConfiguration.Unmarshal(m, b)
}
func (m *DatabaseConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseConfiguration.Marshal(b, m, deterministic)
}
func (m *DatabaseConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseConfiguration.Merge(m, src)
}
func (m *DatabaseConfiguration) XXX_Size() int {
	return xxx_messageInfo_DatabaseConfiguration.Size(m)
}
func (m *DatabaseConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseConfiguration proto.InternalMessageInfo

func (m *DatabaseConfiguration) GetDialect() DatabaseDialect {
	if m != nil {
		return m.Dialect
	}
	return DatabaseDialect_DATABASE_DIALECT_UNSPECIFIED
}

func (m *DatabaseConfiguration) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DatabaseConfiguration) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *DatabaseConfiguration) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DatabaseConfiguration) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DatabaseConfiguration) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *DatabaseConfiguration) GetCharset() string {
	if m != nil {
		return m.Charset
	}
	return ""
}

func (m *DatabaseConfiguration) GetUtc() bool {
	if m != nil {
		return m.Utc
	}
	return false
}

func (m *DatabaseConfiguration) GetLogging() bool {
	if m != nil {
		return m.Logging
	}
	return false
}

func (m *DatabaseConfiguration) GetSingularize() bool {
	if m != nil {
		return m.Singularize
	}
	return false
}

func (m *DatabaseConfiguration) GetMaxOpenConns() uint32 {
	if m != nil {
		return m.MaxOpenConns
	}
	return 0
}

func (m *DatabaseConfiguration) GetMaxIdleConns() uint32 {
	if m != nil {
		return m.MaxIdleConns
	}
	return 0
}

func (m *DatabaseConfiguration) GetConnMaxLifetime() *duration.Duration {
	if m != nil {
		return m.ConnMaxLifetime
	}
	return nil
}

type Features struct {
	Metrics              *Features_Metrics   `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Tracing              *Features_Tracing   `protobuf:"bytes,2,opt,name=tracing,proto3" json:"tracing,omitempty"`
	Tls                  *Features_TLS       `protobuf:"bytes,3,opt,name=tls,proto3" json:"tls,omitempty"`
	Validator            *Features_Validator `protobuf:"bytes,4,opt,name=validator,proto3" json:"validator,omitempty"`
	Reqlogs              *Features_Reqlogs   `protobuf:"bytes,5,opt,name=reqlogs,proto3" json:"reqlogs,omitempty"`
	Translogs            *Features_Translogs `protobuf:"bytes,6,opt,name=translogs,proto3" json:"translogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Features) Reset()         { *m = Features{} }
func (m *Features) String() string { return proto.CompactTextString(m) }
func (*Features) ProtoMessage()    {}
func (*Features) Descriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{3}
}

func (m *Features) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Features.Unmarshal(m, b)
}
func (m *Features) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Features.Marshal(b, m, deterministic)
}
func (m *Features) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Features.Merge(m, src)
}
func (m *Features) XXX_Size() int {
	return xxx_messageInfo_Features.Size(m)
}
func (m *Features) XXX_DiscardUnknown() {
	xxx_messageInfo_Features.DiscardUnknown(m)
}

var xxx_messageInfo_Features proto.InternalMessageInfo

func (m *Features) GetMetrics() *Features_Metrics {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *Features) GetTracing() *Features_Tracing {
	if m != nil {
		return m.Tracing
	}
	return nil
}

func (m *Features) GetTls() *Features_TLS {
	if m != nil {
		return m.Tls
	}
	return nil
}

func (m *Features) GetValidator() *Features_Validator {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *Features) GetReqlogs() *Features_Reqlogs {
	if m != nil {
		return m.Reqlogs
	}
	return nil
}

func (m *Features) GetTranslogs() *Features_Translogs {
	if m != nil {
		return m.Translogs
	}
	return nil
}

type Features_Metrics struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	FlushInterval        uint64   `protobuf:"varint,3,opt,name=flush_interval,json=flushInterval,proto3" json:"flush_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Features_Metrics) Reset()         { *m = Features_Metrics{} }
func (m *Features_Metrics) String() string { return proto.CompactTextString(m) }
func (*Features_Metrics) ProtoMessage()    {}
func (*Features_Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{3, 0}
}

func (m *Features_Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Features_Metrics.Unmarshal(m, b)
}
func (m *Features_Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Features_Metrics.Marshal(b, m, deterministic)
}
func (m *Features_Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Features_Metrics.Merge(m, src)
}
func (m *Features_Metrics) XXX_Size() int {
	return xxx_messageInfo_Features_Metrics.Size(m)
}
func (m *Features_Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Features_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Features_Metrics proto.InternalMessageInfo

func (m *Features_Metrics) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Features_Metrics) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Features_Metrics) GetFlushInterval() uint64 {
	if m != nil {
		return m.FlushInterval
	}
	return 0
}

type Features_Tracing struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	FlushInterval        uint64   `protobuf:"varint,3,opt,name=flush_interval,json=flushInterval,proto3" json:"flush_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Features_Tracing) Reset()         { *m = Features_Tracing{} }
func (m *Features_Tracing) String() string { return proto.CompactTextString(m) }
func (*Features_Tracing) ProtoMessage()    {}
func (*Features_Tracing) Descriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{3, 1}
}

func (m *Features_Tracing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Features_Tracing.Unmarshal(m, b)
}
func (m *Features_Tracing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Features_Tracing.Marshal(b, m, deterministic)
}
func (m *Features_Tracing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Features_Tracing.Merge(m, src)
}
func (m *Features_Tracing) XXX_Size() int {
	return xxx_messageInfo_Features_Tracing.Size(m)
}
func (m *Features_Tracing) XXX_DiscardUnknown() {
	xxx_messageInfo_Features_Tracing.DiscardUnknown(m)
}

var xxx_messageInfo_Features_Tracing proto.InternalMessageInfo

func (m *Features_Tracing) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Features_Tracing) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Features_Tracing) GetFlushInterval() uint64 {
	if m != nil {
		return m.FlushInterval
	}
	return 0
}

type Features_TLS struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CertFile             string   `protobuf:"bytes,2,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile              string   `protobuf:"bytes,3,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	CaFile               string   `protobuf:"bytes,4,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	Servername           string   `protobuf:"bytes,5,opt,name=servername,proto3" json:"servername,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Features_TLS) Reset()         { *m = Features_TLS{} }
func (m *Features_TLS) String() string { return proto.CompactTextString(m) }
func (*Features_TLS) ProtoMessage()    {}
func (*Features_TLS) Descriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{3, 2}
}

func (m *Features_TLS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Features_TLS.Unmarshal(m, b)
}
func (m *Features_TLS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Features_TLS.Marshal(b, m, deterministic)
}
func (m *Features_TLS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Features_TLS.Merge(m, src)
}
func (m *Features_TLS) XXX_Size() int {
	return xxx_messageInfo_Features_TLS.Size(m)
}
func (m *Features_TLS) XXX_DiscardUnknown() {
	xxx_messageInfo_Features_TLS.DiscardUnknown(m)
}

var xxx_messageInfo_Features_TLS proto.InternalMessageInfo

func (m *Features_TLS) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Features_TLS) GetCertFile() string {
	if m != nil {
		return m.CertFile
	}
	return ""
}

func (m *Features_TLS) GetKeyFile() string {
	if m != nil {
		return m.KeyFile
	}
	return ""
}

func (m *Features_TLS) GetCaFile() string {
	if m != nil {
		return m.CaFile
	}
	return ""
}

func (m *Features_TLS) GetServername() string {
	if m != nil {
		return m.Servername
	}
	return ""
}

type Features_Validator struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Features_Validator) Reset()         { *m = Features_Validator{} }
func (m *Features_Validator) String() string { return proto.CompactTextString(m) }
func (*Features_Validator) ProtoMessage()    {}
func (*Features_Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{3, 3}
}

func (m *Features_Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Features_Validator.Unmarshal(m, b)
}
func (m *Features_Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Features_Validator.Marshal(b, m, deterministic)
}
func (m *Features_Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Features_Validator.Merge(m, src)
}
func (m *Features_Validator) XXX_Size() int {
	return xxx_messageInfo_Features_Validator.Size(m)
}
func (m *Features_Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Features_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Features_Validator proto.InternalMessageInfo

func (m *Features_Validator) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type Features_Reqlogs struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Features_Reqlogs) Reset()         { *m = Features_Reqlogs{} }
func (m *Features_Reqlogs) String() string { return proto.CompactTextString(m) }
func (*Features_Reqlogs) ProtoMessage()    {}
func (*Features_Reqlogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{3, 4}
}

func (m *Features_Reqlogs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Features_Reqlogs.Unmarshal(m, b)
}
func (m *Features_Reqlogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Features_Reqlogs.Marshal(b, m, deterministic)
}
func (m *Features_Reqlogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Features_Reqlogs.Merge(m, src)
}
func (m *Features_Reqlogs) XXX_Size() int {
	return xxx_messageInfo_Features_Reqlogs.Size(m)
}
func (m *Features_Reqlogs) XXX_DiscardUnknown() {
	xxx_messageInfo_Features_Reqlogs.DiscardUnknown(m)
}

var xxx_messageInfo_Features_Reqlogs proto.InternalMessageInfo

func (m *Features_Reqlogs) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type Features_Translogs struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Features_Translogs) Reset()         { *m = Features_Translogs{} }
func (m *Features_Translogs) String() string { return proto.CompactTextString(m) }
func (*Features_Translogs) ProtoMessage()    {}
func (*Features_Translogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{3, 5}
}

func (m *Features_Translogs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Features_Translogs.Unmarshal(m, b)
}
func (m *Features_Translogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Features_Translogs.Marshal(b, m, deterministic)
}
func (m *Features_Translogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Features_Translogs.Merge(m, src)
}
func (m *Features_Translogs) XXX_Size() int {
	return xxx_messageInfo_Features_Translogs.Size(m)
}
func (m *Features_Translogs) XXX_DiscardUnknown() {
	xxx_messageInfo_Features_Translogs.DiscardUnknown(m)
}

var xxx_messageInfo_Features_Translogs proto.InternalMessageInfo

func (m *Features_Translogs) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Features_Translogs) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type Services struct {
	Account              *Service `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Greeter              *Service `protobuf:"bytes,2,opt,name=greeter,proto3" json:"greeter,omitempty"`
	Emailer              *Service `protobuf:"bytes,3,opt,name=emailer,proto3" json:"emailer,omitempty"`
	Recorder             *Service `protobuf:"bytes,4,opt,name=recorder,proto3" json:"recorder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Services) Reset()         { *m = Services{} }
func (m *Services) String() string { return proto.CompactTextString(m) }
func (*Services) ProtoMessage()    {}
func (*Services) Descriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{4}
}

func (m *Services) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Services.Unmarshal(m, b)
}
func (m *Services) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Services.Marshal(b, m, deterministic)
}
func (m *Services) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Services.Merge(m, src)
}
func (m *Services) XXX_Size() int {
	return xxx_messageInfo_Services.Size(m)
}
func (m *Services) XXX_DiscardUnknown() {
	xxx_messageInfo_Services.DiscardUnknown(m)
}

var xxx_messageInfo_Services proto.InternalMessageInfo

func (m *Services) GetAccount() *Service {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Services) GetGreeter() *Service {
	if m != nil {
		return m.Greeter
	}
	return nil
}

func (m *Services) GetEmailer() *Service {
	if m != nil {
		return m.Emailer
	}
	return nil
}

func (m *Services) GetRecorder() *Service {
	if m != nil {
		return m.Recorder
	}
	return nil
}

type Configuration struct {
	Database             *DatabaseConfiguration `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Email                *EmailConfiguration    `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Features             *Features              `protobuf:"bytes,5,opt,name=features,proto3" json:"features,omitempty"`
	Services             *Services              `protobuf:"bytes,6,opt,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_f590afff4cf83464, []int{5}
}

func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (m *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(m, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetDatabase() *DatabaseConfiguration {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *Configuration) GetEmail() *EmailConfiguration {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *Configuration) GetFeatures() *Features {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *Configuration) GetServices() *Services {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterEnum("mkit.shared.config.v1.DatabaseDialect", DatabaseDialect_name, DatabaseDialect_value)
	proto.RegisterType((*Service)(nil), "mkit.shared.config.v1.Service")
	proto.RegisterType((*EmailConfiguration)(nil), "mkit.shared.config.v1.EmailConfiguration")
	proto.RegisterType((*DatabaseConfiguration)(nil), "mkit.shared.config.v1.DatabaseConfiguration")
	proto.RegisterType((*Features)(nil), "mkit.shared.config.v1.Features")
	proto.RegisterType((*Features_Metrics)(nil), "mkit.shared.config.v1.Features.Metrics")
	proto.RegisterType((*Features_Tracing)(nil), "mkit.shared.config.v1.Features.Tracing")
	proto.RegisterType((*Features_TLS)(nil), "mkit.shared.config.v1.Features.TLS")
	proto.RegisterType((*Features_Validator)(nil), "mkit.shared.config.v1.Features.Validator")
	proto.RegisterType((*Features_Reqlogs)(nil), "mkit.shared.config.v1.Features.Reqlogs")
	proto.RegisterType((*Features_Translogs)(nil), "mkit.shared.config.v1.Features.Translogs")
	proto.RegisterType((*Services)(nil), "mkit.shared.config.v1.Services")
	proto.RegisterType((*Configuration)(nil), "mkit.shared.config.v1.Configuration")
}

func init() {
	proto.RegisterFile("mkit/shared/config/v1/config.proto", fileDescriptor_f590afff4cf83464)
}

var fileDescriptor_f590afff4cf83464 = []byte{
	// 1408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x97, 0xcd, 0x6e, 0x1b, 0xb7,
	0x16, 0xc7, 0xef, 0x58, 0xb6, 0x35, 0xa6, 0xe2, 0xc4, 0x97, 0xf9, 0x9a, 0x28, 0x1f, 0xa3, 0x30,
	0xb9, 0x37, 0x4e, 0xae, 0xaf, 0x64, 0xcb, 0xcd, 0x97, 0x8b, 0xc4, 0xb0, 0x64, 0xc5, 0x75, 0x21,
	0x37, 0x36, 0xe5, 0x14, 0x68, 0x81, 0x42, 0xa0, 0x67, 0x28, 0x79, 0x90, 0xd1, 0x8c, 0xc2, 0xa1,
	0xd4, 0xb8, 0x08, 0xba, 0x29, 0xba, 0xec, 0xaa, 0x9b, 0x66, 0xd3, 0x97, 0xe9, 0xaa, 0x2f, 0x31,
	0x7d, 0x87, 0x41, 0x0b, 0x74, 0x59, 0x0c, 0xc9, 0x51, 0x64, 0x4b, 0xb2, 0x54, 0x78, 0x55, 0xad,
	0x44, 0x9c, 0xff, 0xef, 0x90, 0xe7, 0x90, 0x87, 0x3c, 0x03, 0x50, 0xeb, 0xb5, 0xc3, 0x0b, 0xc1,
	0x21, 0x61, 0xd4, 0x2e, 0x58, 0xbe, 0xd7, 0x70, 0x9a, 0x85, 0xee, 0x8a, 0xfa, 0x97, 0x6f, 0x33,
	0x9f, 0xfb, 0xf0, 0x72, 0xac, 0xc9, 0x4b, 0x4d, 0x5e, 0x59, 0xba, 0x2b, 0xd9, 0x4b, 0x4d, 0xbf,
	0xe9, 0x0b, 0x45, 0x21, 0xfe, 0x27, 0xc5, 0xd9, 0x5b, 0x4d, 0xdf, 0x6f, 0xba, 0xb4, 0x20, 0x46,
	0x07, 0x9d, 0x46, 0xc1, 0xee, 0x30, 0xc2, 0x1d, 0xdf, 0x53, 0xf6, 0xeb, 0x27, 0xed, 0xb4, 0xd5,
	0xe6, 0x47, 0xca, 0x78, 0xb5, 0x4b, 0x5c, 0xc7, 0x26, 0x9c, 0x16, 0x92, 0x3f, 0xd2, 0x80, 0x7e,
	0xd5, 0x40, 0xba, 0x46, 0x59, 0xd7, 0xb1, 0x28, 0x5c, 0x07, 0x3a, 0xf5, 0xec, 0xb6, 0xef, 0x78,
	0xdc, 0xd0, 0x72, 0xda, 0xe2, 0x5c, 0xe9, 0x4e, 0x14, 0x9a, 0xe6, 0x11, 0x69, 0xb9, 0x6b, 0x28,
	0xb1, 0xa0, 0x1c, 0xa3, 0x6f, 0x3a, 0x0e, 0xa3, 0xf6, 0x1a, 0xe2, 0xac, 0x43, 0x11, 0xee, 0x41,
	0xf0, 0x19, 0x48, 0x77, 0x29, 0x0b, 0x1c, 0xdf, 0x33, 0xa6, 0x4e, 0xf2, 0xca, 0x80, 0x72, 0x36,
	0x6d, 0x90, 0x8e, 0xcb, 0xd7, 0x50, 0x77, 0x39, 0xbf, 0x92, 0x5f, 0x46, 0x38, 0x61, 0xe0, 0x73,
	0xa0, 0xdb, 0x94, 0xd8, 0xae, 0xe3, 0x51, 0x23, 0x95, 0xd3, 0x16, 0xe7, 0x4b, 0x28, 0x0a, 0xcd,
	0x5b, 0x92, 0x5f, 0xf2, 0x5b, 0x0e, 0x17, 0x21, 0xf5, 0xb9, 0x58, 0x59, 0x46, 0xb8, 0xc7, 0xa0,
	0x1f, 0xa7, 0x00, 0xac, 0xb4, 0x88, 0xe3, 0x96, 0x45, 0x2a, 0x55, 0x7a, 0x60, 0x01, 0xe8, 0x9d,
	0x80, 0x32, 0x8f, 0xb4, 0xa8, 0x0a, 0xeb, 0x62, 0x14, 0x9a, 0x17, 0xa4, 0xdb, 0xc4, 0x82, 0x70,
	0x4f, 0x04, 0xb3, 0x40, 0x6f, 0x93, 0x20, 0xf8, 0xda, 0x67, 0xb6, 0x8c, 0x03, 0xf7, 0xc6, 0x70,
	0x0d, 0x9c, 0xa3, 0xf1, 0x14, 0xf5, 0x80, 0xb2, 0x2e, 0x65, 0x62, 0x9d, 0x73, 0xa5, 0xab, 0x51,
	0x68, 0x5e, 0x54, 0x79, 0xea, 0xb3, 0x22, 0x9c, 0x11, 0xc3, 0x9a, 0x18, 0xc1, 0x4d, 0x30, 0xdd,
	0xf6, 0x19, 0x37, 0xa6, 0x45, 0x6c, 0xcb, 0x51, 0x68, 0x2e, 0x9d, 0x12, 0xdb, 0xc3, 0x27, 0x8f,
	0x51, 0x4e, 0xec, 0xd6, 0x1a, 0x8a, 0x31, 0x84, 0x05, 0x0d, 0xf3, 0x60, 0xba, 0xc1, 0xfc, 0x96,
	0x31, 0x23, 0x66, 0xce, 0x46, 0xa1, 0x79, 0x45, 0xa9, 0xc4, 0x5c, 0x4b, 0x7e, 0x3b, 0x8e, 0x9a,
	0xb8, 0x08, 0x0b, 0x1d, 0xfa, 0x4e, 0x07, 0x97, 0x37, 0x09, 0x27, 0x07, 0x24, 0xa0, 0xc7, 0x13,
	0xf3, 0xbd, 0x06, 0xd2, 0xb6, 0x43, 0x5c, 0x6a, 0xc9, 0xfd, 0x3e, 0x5f, 0xfc, 0x6f, 0x7e, 0xe8,
	0x89, 0xcc, 0x27, 0xfc, 0xa6, 0x54, 0x97, 0xca, 0x51, 0x68, 0xae, 0x0f, 0xae, 0x5d, 0xad, 0xc3,
	0xf1, 0x16, 0x77, 0xfd, 0x80, 0x37, 0x19, 0x7d, 0xb7, 0x73, 0x54, 0xdb, 0xab, 0xbe, 0xab, 0xed,
	0x55, 0x1d, 0x4e, 0x57, 0xef, 0xf7, 0x45, 0x57, 0x44, 0x38, 0x99, 0x1b, 0x3e, 0x02, 0xd3, 0x87,
	0x7e, 0xc0, 0xd5, 0x99, 0x19, 0xb1, 0xe7, 0xca, 0x77, 0x2c, 0x44, 0x58, 0xe8, 0x61, 0x45, 0xe5,
	0x53, 0x9e, 0x95, 0x95, 0x28, 0x34, 0xff, 0x7f, 0x5a, 0x3e, 0x3f, 0x5a, 0x2d, 0x0e, 0x4d, 0xe8,
	0xd3, 0xbe, 0xf3, 0x31, 0x2d, 0x96, 0x70, 0x33, 0x0a, 0xcd, 0x6b, 0x4a, 0x49, 0xdc, 0xf6, 0x21,
	0xf1, 0x3a, 0xad, 0xa5, 0xe4, 0xd8, 0xf7, 0x9f, 0x94, 0xa7, 0x7d, 0x27, 0x65, 0x66, 0x22, 0xb4,
	0x77, 0x90, 0x9e, 0x01, 0xdd, 0x56, 0x59, 0x35, 0x66, 0x05, 0x7a, 0x3b, 0x0a, 0xcd, 0x9b, 0x0a,
	0xe5, 0x47, 0x6d, 0xba, 0x18, 0x70, 0xe6, 0x78, 0xcd, 0xfb, 0xfd, 0x78, 0x82, 0xc0, 0xe7, 0x20,
	0x6d, 0x1d, 0x12, 0x16, 0x50, 0x6e, 0xa4, 0x05, 0x7d, 0x37, 0x0a, 0xcd, 0xdc, 0x29, 0xe1, 0x77,
	0x78, 0xe3, 0x09, 0xc2, 0x09, 0x04, 0x1f, 0x81, 0x54, 0x87, 0x5b, 0x86, 0x9e, 0xd3, 0x16, 0xf5,
	0xb1, 0xac, 0xac, 0xf3, 0x18, 0x80, 0xeb, 0x20, 0xed, 0xfa, 0xcd, 0xa6, 0xe3, 0x35, 0x8d, 0x39,
	0xc1, 0xfe, 0x27, 0x0a, 0xcd, 0xdb, 0xa7, 0xb0, 0x0d, 0xe2, 0x06, 0x14, 0xe1, 0x84, 0x82, 0x5b,
	0x20, 0x13, 0x38, 0x5e, 0xb3, 0xe3, 0x12, 0xe6, 0x7c, 0x43, 0x0d, 0xf0, 0x77, 0x9c, 0xf4, 0x93,
	0xf0, 0x15, 0x38, 0xdf, 0x22, 0x6f, 0xeb, 0x7e, 0x9b, 0x7a, 0x75, 0xcb, 0xf7, 0xbc, 0xc0, 0xc8,
	0x88, 0x73, 0x50, 0x88, 0x42, 0xf3, 0x7f, 0xd2, 0xd7, 0x71, 0xfb, 0xf0, 0x1b, 0x04, 0xe1, 0x73,
	0x2d, 0xf2, 0xf6, 0x65, 0x9b, 0x7a, 0xe5, 0x58, 0x94, 0xb8, 0x75, 0x6c, 0x97, 0x2a, 0xb7, 0xe7,
	0x86, 0xb9, 0xfd, 0x60, 0x3f, 0xcd, 0xed, 0xb6, 0xed, 0x52, 0xe9, 0xf6, 0x5b, 0xf0, 0xef, 0x58,
	0x5d, 0x8f, 0x59, 0xd7, 0x69, 0x50, 0xee, 0xb4, 0xa8, 0x31, 0x9f, 0xd3, 0x16, 0x33, 0xc5, 0x6b,
	0x79, 0x79, 0x73, 0xe7, 0x93, 0x9b, 0x3b, 0xbf, 0xa9, 0x2a, 0xb4, 0xf4, 0x38, 0x0a, 0xcd, 0x82,
	0x9c, 0x74, 0x80, 0x1e, 0x3e, 0xef, 0x21, 0xfa, 0xe9, 0x37, 0x53, 0xc3, 0x17, 0x62, 0xf9, 0x0e,
	0x79, 0x5b, 0x55, 0x62, 0xf4, 0x73, 0x06, 0xe8, 0x2f, 0x28, 0xe1, 0x1d, 0x46, 0x03, 0xb8, 0x01,
	0xd2, 0x2d, 0xca, 0x99, 0x63, 0x05, 0xa2, 0xee, 0x33, 0xc5, 0x7b, 0x23, 0xea, 0x3e, 0x21, 0xf2,
	0x3b, 0x52, 0x8e, 0x13, 0x2e, 0x76, 0xc1, 0x19, 0xb1, 0xe2, 0x73, 0x30, 0x35, 0x99, 0x8b, 0x7d,
	0x29, 0xc7, 0x09, 0x07, 0x1f, 0x82, 0x14, 0x77, 0x03, 0x51, 0xbd, 0x99, 0xe2, 0x9d, 0xb1, 0x78,
	0xb5, 0x86, 0x63, 0x3d, 0xdc, 0x02, 0x73, 0xea, 0x0d, 0xf3, 0x99, 0xa8, 0xd7, 0x4c, 0xf1, 0xfe,
	0x38, 0xf8, 0xf3, 0x04, 0xc0, 0x1f, 0xd8, 0x38, 0x04, 0x46, 0xdf, 0xb8, 0x7e, 0x33, 0x10, 0xb5,
	0x3b, 0x41, 0x08, 0x58, 0xca, 0x71, 0xc2, 0xc5, 0x6b, 0xe1, 0x8c, 0x78, 0x81, 0x70, 0x32, 0x3b,
	0xd9, 0x5a, 0xf6, 0x13, 0x00, 0x7f, 0x60, 0xb3, 0xbf, 0x68, 0x20, 0xad, 0x72, 0x1c, 0x97, 0x18,
	0xf5, 0xc8, 0x81, 0x4b, 0x6d, 0xb1, 0x3b, 0x93, 0x97, 0x98, 0xa2, 0xa0, 0x01, 0xd2, 0xc4, 0xb6,
	0x19, 0x0d, 0x02, 0xf5, 0x7c, 0x25, 0x43, 0xf8, 0x15, 0x38, 0xdf, 0x70, 0x3b, 0xc1, 0x61, 0xdd,
	0xf1, 0x38, 0x65, 0x5d, 0xe2, 0x8a, 0xec, 0x4f, 0x97, 0x1e, 0x45, 0xa1, 0x59, 0x94, 0x33, 0x1c,
	0xb7, 0x8f, 0x78, 0x75, 0xe5, 0x0f, 0xe1, 0x79, 0xa1, 0xde, 0x56, 0x62, 0x11, 0x85, 0xda, 0xe6,
	0x7f, 0x70, 0x14, 0x7f, 0x4c, 0x81, 0xd4, 0x7e, 0xb5, 0x76, 0xf6, 0x08, 0x5e, 0x82, 0x39, 0x8b,
	0x32, 0x5e, 0x6f, 0x38, 0x2e, 0x55, 0x8f, 0x5b, 0x31, 0x0a, 0xcd, 0xbc, 0x2a, 0xe8, 0xc4, 0xd4,
	0x7b, 0x94, 0x46, 0x5d, 0xfa, 0xb1, 0xf2, 0x85, 0xe3, 0x52, 0x58, 0x05, 0xfa, 0x6b, 0x7a, 0x24,
	0xfd, 0xc9, 0xc6, 0xa3, 0xef, 0xd1, 0x4b, 0x2c, 0xe3, 0xdc, 0xa5, 0x5f, 0xd3, 0x23, 0xe1, 0x6d,
	0x1b, 0xa4, 0x2d, 0x22, 0x9d, 0xc9, 0x67, 0xaf, 0xaf, 0x23, 0x51, 0x86, 0x71, 0xbe, 0x66, 0x2d,
	0x22, 0x5c, 0x95, 0x01, 0x90, 0x1d, 0x8f, 0x78, 0x44, 0x67, 0x4e, 0xf6, 0x7e, 0x43, 0xb3, 0x75,
	0xef, 0xc1, 0x3d, 0x84, 0xfb, 0xb0, 0x6c, 0x15, 0xcc, 0xf5, 0xea, 0xf4, 0xcc, 0xc9, 0xcf, 0x7e,
	0x0a, 0xd2, 0xaa, 0x5c, 0xcf, 0xee, 0xeb, 0x00, 0xcc, 0xf5, 0xaa, 0xf6, 0xec, 0xc7, 0xe2, 0x12,
	0x98, 0xe1, 0x7e, 0xdb, 0xb1, 0xd4, 0xb1, 0x96, 0x03, 0xf4, 0xbb, 0x06, 0x74, 0xd5, 0x88, 0x07,
	0xf0, 0x09, 0x48, 0x13, 0xcb, 0xf2, 0x3b, 0xaa, 0x11, 0xcf, 0x14, 0x6f, 0x8d, 0xb8, 0x55, 0x14,
	0x81, 0x13, 0x79, 0x4c, 0x36, 0x19, 0xa5, 0x9c, 0x32, 0x75, 0x2f, 0x8f, 0x25, 0x95, 0x3c, 0x26,
	0x45, 0x03, 0xa9, 0x9a, 0xda, 0x09, 0x48, 0x25, 0x87, 0x6b, 0x40, 0x67, 0xd4, 0xf2, 0x99, 0x4d,
	0x93, 0x0b, 0x79, 0x1c, 0xda, 0xd3, 0xa3, 0xf7, 0x53, 0x60, 0xfe, 0x78, 0x57, 0xfa, 0x49, 0x5f,
	0x63, 0x24, 0x17, 0xb2, 0x34, 0xa6, 0x2b, 0x3d, 0xc6, 0xf7, 0xf5, 0x48, 0xeb, 0x60, 0x46, 0x2c,
	0x71, 0xcc, 0x2b, 0x31, 0xf8, 0xc9, 0x80, 0x25, 0x07, 0x3f, 0x06, 0x7a, 0x43, 0x5d, 0xdb, 0xea,
	0x89, 0x30, 0xc7, 0xdc, 0xee, 0xb8, 0x07, 0xc4, 0x70, 0xa0, 0xf6, 0x53, 0x3d, 0x0d, 0xe6, 0xe9,
	0x59, 0x09, 0x70, 0x0f, 0x58, 0x4b, 0xfd, 0x59, 0xd2, 0x1e, 0xfc, 0xa0, 0x81, 0x0b, 0x27, 0x3a,
	0x6f, 0x98, 0x03, 0x37, 0x36, 0x37, 0xf6, 0x37, 0x4a, 0x1b, 0xb5, 0x4a, 0x7d, 0x73, 0x7b, 0xa3,
	0x5a, 0x29, 0xef, 0xd7, 0x5f, 0x7d, 0x56, 0xdb, 0xad, 0x94, 0xb7, 0x5f, 0x6c, 0x57, 0x36, 0x17,
	0xfe, 0x05, 0x6f, 0x00, 0x63, 0x40, 0xb1, 0xfb, 0xb2, 0xb6, 0xbf, 0x85, 0x2b, 0x0b, 0x1a, 0xbc,
	0x0e, 0xae, 0x0e, 0x58, 0x77, 0xbe, 0xa8, 0xd7, 0xf6, 0xaa, 0x0b, 0x53, 0xf0, 0x26, 0xb8, 0x36,
	0x60, 0xac, 0xed, 0xd5, 0xab, 0xdb, 0xfb, 0x95, 0xd5, 0x85, 0x54, 0xf1, 0xbd, 0x96, 0xec, 0x55,
	0xf2, 0xc5, 0x58, 0x06, 0xa9, 0x2d, 0xca, 0xe1, 0x95, 0x81, 0x0e, 0xa6, 0x12, 0xd7, 0x40, 0xf6,
	0xee, 0x88, 0x80, 0x8f, 0x6f, 0x78, 0x19, 0xa4, 0x6a, 0x94, 0xc3, 0x89, 0xc4, 0xd9, 0x11, 0x53,
	0x95, 0xee, 0x80, 0xe1, 0x1f, 0xd3, 0xbb, 0xda, 0x97, 0xba, 0x1c, 0x74, 0x57, 0x0e, 0x66, 0x05,
	0xb4, 0xfa, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0xf6, 0x5d, 0x0b, 0x9c, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigServiceClient interface {
	Get(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Configuration, error)
	Set(ctx context.Context, in *Configuration, opts ...grpc.CallOption) (*empty.Empty, error)
}

type configServiceClient struct {
	cc *grpc.ClientConn
}

func NewConfigServiceClient(cc *grpc.ClientConn) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) Get(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Configuration, error) {
	out := new(Configuration)
	err := c.cc.Invoke(ctx, "/mkit.shared.config.v1.ConfigService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) Set(ctx context.Context, in *Configuration, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/mkit.shared.config.v1.ConfigService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
type ConfigServiceServer interface {
	Get(context.Context, *empty.Empty) (*Configuration, error)
	Set(context.Context, *Configuration) (*empty.Empty, error)
}

// UnimplementedConfigServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConfigServiceServer struct {
}

func (*UnimplementedConfigServiceServer) Get(ctx context.Context, req *empty.Empty) (*Configuration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedConfigServiceServer) Set(ctx context.Context, req *Configuration) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}

func RegisterConfigServiceServer(s *grpc.Server, srv ConfigServiceServer) {
	s.RegisterService(&_ConfigService_serviceDesc, srv)
}

func _ConfigService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mkit.shared.config.v1.ConfigService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).Get(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Configuration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mkit.shared.config.v1.ConfigService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).Set(ctx, req.(*Configuration))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfigService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mkit.shared.config.v1.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ConfigService_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _ConfigService_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mkit/shared/config/v1/config.proto",
}
