apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xds
rules:
  - apiGroups: [""]
    resources: ["endpoints", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xds
subjects:
  - kind: ServiceAccount
    name: xds
    namespace: default
roleRef:
  kind: ClusterRole
  name: xds
  apiGroup: rbac.authorization.k8s.io
