on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

name: Vulnerability Scanning

jobs:

  codeql:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'go'

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v1
