name: Proto
on:
  push:
    paths:
      - '**.proto'
jobs:
  build:
    runs-on: ubuntu-latest
#    container: bufbuild/buf
    steps:
      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: '3.x'
      - name: Install buf
        uses: wizhi/setup-buf@v1
        with:
          version: 0.35.1

      - name: checkout
        uses: actions/checkout@v2.4.0

      - name: proto check
        run: |
          task proto:check
  protogen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
        run: |
          task proto:default
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: commit-changes
        with:
          commit_message: Commit changes in updated/new protobuf files
