// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
